// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/12/2026, 3:49:56 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Applications/XAMPP/xamppfiles/htdocs/beatMai/home/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/beatMai/home/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/beatMai/home/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/beatMai/home/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/beatMai/home/plugins/**/*.{js,ts,mjs}","/Applications/XAMPP/xamppfiles/htdocs/beatMai/home/composables/**/*.{js,ts,mjs}","/Applications/XAMPP/xamppfiles/htdocs/beatMai/home/utils/**/*.{js,ts,mjs}","/Applications/XAMPP/xamppfiles/htdocs/beatMai/home/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/beatMai/home/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/beatMai/home/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/beatMai/home/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;